# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# настройка для генерации с базой tracker.
services:
  - postgresql

before_install:
  - psql -c 'create database forum;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление, если сборка упала, на почту youremail@smtp.ru(Изменить на свою)
notifications:
  email:
    recipients:
      -dmstrannik@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="940c0bbb-5dfe-4b9c-9d51-61acd9c0d5d9"